src = $(wildcard *.c)

CPU ?= 060
ifeq ($(CPU), cf)
	cpuflags = -mcpu=5475 -mfastcall
	o = atc
else
	cpuflags = -m68020-60 -mtune=68060 -mfastcall
	o = ato
endif

obj = $(src:.c=.$(o))
alib = assfile-$(CPU).ata

TOOLPREFIX = m68k-atari-mintelf-
CC = $(TOOLPREFIX)gcc
AR = $(TOOLPREFIX)ar
CFLAGS = $(cpuflags) -O2 -fomit-frame-pointer -Wno-main

$(alib): $(obj)
	$(AR) rcs $@ $(obj)

%.$(o): %.c
	$(CC) $(CFLAGS) -o $@ -c $<

.PHONY: clean
clean:
	rm -f $(obj) $(alib)
